# Generated by Django 4.2.10 on 2024-11-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0011_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('purchasedate', models.DateField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('plan', models.CharField(max_length=100, null=True)),
                ('joindate', models.DateField(null=True)),
                ('initamount', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
