# Generated by Django 4.2.10 on 2024-11-22 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backendapp', '0015_alter_members_plan_delete_memberplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRecoveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('recovery_requested_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Recovery Request',
                'verbose_name_plural': 'Password Recovery Requests',
            },
        ),
    ]
